const sportsProducts = [
    {
        name: "Nike Air Zoom Pegasus 40 Running Shoes",
        price: 129.99,
        description: "Lightweight and responsive running shoes with Nike's signature Zoom Air cushioning for optimal performance and comfort during long runs.",
        image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff",
        category: "Sports",
        brand: "Nike",
        tags: ["running", "shoes", "athletic", "fitness"],
        rating: 4.7,
        reviewCount: 2843,
        inStock: true,
        priceRange: "$100-$150",
        views: 15420,
        clicks: 3240,
        purchases: 892,
        embedding: []
    },
    {
        name: "Adidas Tiro 23 Training Pants",
        price: 44.99,
        description: "Comfortable training pants with moisture-wicking fabric and tapered fit. Perfect for practice sessions and casual wear.",
        image: "https://images.unsplash.com/photo-1556821840-3a63f95609a7",
        category: "Sports",
        brand: "Adidas",
        tags: ["training", "pants", "athletic wear", "soccer"],
        rating: 4.5,
        reviewCount: 1567,
        inStock: true,
        priceRange: "$40-$50",
        views: 8932,
        clicks: 1876,
        purchases: 543,
        embedding: []
    },
    {
        name: "Wilson Evolution Indoor Basketball",
        price: 64.99,
        description: "Official size indoor basketball with superior grip and moisture-wicking composite leather cover. The #1 choice for high school and college basketball.",
        image: "https://images.unsplash.com/photo-1546519638-68e109498ffc",
        category: "Sports",
        brand: "Wilson",
        tags: ["basketball", "indoor", "official size", "competition"],
        rating: 4.8,
        reviewCount: 3291,
        inStock: true,
        priceRange: "$60-$70",
        views: 12453,
        clicks: 2987,
        purchases: 1124,
        embedding: []
    },
    {
        name: "Yonex Badminton Racket - Nanoray Series",
        price: 89.99,
        description: "Professional-grade badminton racket with lightweight carbon frame and enhanced repulsion power for aggressive play.",
        image: "https://images.unsplash.com/photo-1626224583764-f87db24ac4ea",
        category: "Sports",
        brand: "Yonex",
        tags: ["badminton", "racket", "professional", "carbon fiber"],
        rating: 4.6,
        reviewCount: 892,
        inStock: true,
        priceRange: "$80-$100",
        views: 5621,
        clicks: 1243,
        purchases: 378,
        embedding: []
    },
    {
        name: "Speedo Vanquisher 2.0 Swim Goggles",
        price: 19.99,
        description: "Anti-fog swim goggles with UV protection and comfortable silicone gaskets. Perfect for training and competition.",
        image: "https://images.unsplash.com/photo-1530549387789-4c1017266635",
        category: "Sports",
        brand: "Speedo",
        tags: ["swimming", "goggles", "water sports", "training"],
        rating: 4.4,
        reviewCount: 2156,
        inStock: true,
        priceRange: "$15-$25",
        views: 9874,
        clicks: 2341,
        purchases: 876,
        embedding: []
    },
    {
        name: "Manduka PRO Yoga Mat",
        price: 118.00,
        description: "Premium 6mm thick yoga mat with superior cushioning and grip. Eco-friendly and built to last a lifetime.",
        image: "https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f",
        category: "Sports",
        brand: "Manduka",
        tags: ["yoga", "mat", "fitness", "eco-friendly"],
        rating: 4.9,
        reviewCount: 4521,
        inStock: true,
        priceRange: "$100-$150",
        views: 18932,
        clicks: 4231,
        purchases: 1543,
        embedding: []
    },
    {
        name: "Callaway Golf Club Set - 11 Piece",
        price: 499.99,
        description: "Complete golf club set including driver, woods, irons, wedges, putter, and stand bag. Perfect for beginners and intermediate players.",
        image: "https://images.unsplash.com/photo-1535131749006-b7f58c99034b",
        category: "Sports",
        brand: "Callaway",
        tags: ["golf", "clubs", "complete set", "beginners"],
        rating: 4.7,
        reviewCount: 1876,
        inStock: true,
        priceRange: "$400-$600",
        views: 7654,
        clicks: 1432,
        purchases: 234,
        embedding: []
    },
    {
        name: "Harbinger Power Lifting Straps",
        price: 14.99,
        description: "Heavy-duty weightlifting straps with reinforced stitching and neoprene padding for maximum grip support during deadlifts and rows.",
        image: "https://images.unsplash.com/photo-1517836357463-d25dfeac3438",
        category: "Sports",
        brand: "Harbinger",
        tags: ["weightlifting", "straps", "gym", "powerlifting"],
        rating: 4.6,
        reviewCount: 3421,
        inStock: true,
        priceRange: "$10-$20",
        views: 11234,
        clicks: 2876,
        purchases: 1087,
        embedding: []
    },
    {
        name: "Coleman 6-Person Camping Tent",
        price: 159.99,
        description: "Spacious dome tent with weather-resistant fabric and easy setup. Includes room divider and storage pockets.",
        image: "https://images.unsplash.com/photo-1504280390367-361c6d9f38f4",
        category: "Sports",
        brand: "Coleman",
        tags: ["camping", "tent", "outdoor", "family"],
        rating: 4.5,
        reviewCount: 2987,
        inStock: true,
        priceRange: "$150-$200",
        views: 13456,
        clicks: 3124,
        purchases: 765,
        embedding: []
    },
    {
        name: "Head MX Spark Elite Tennis Racket",
        price: 179.99,
        description: "Lightweight aluminum tennis racket with oversize head for power and forgiveness. Great for recreational players.",
        image: "https://images.unsplash.com/photo-1622279457486-62dcc4a431d6",
        category: "Sports",
        brand: "Head",
        tags: ["tennis", "racket", "recreational", "aluminum"],
        rating: 4.4,
        reviewCount: 1234,
        inStock: true,
        priceRange: "$150-$200",
        views: 6789,
        clicks: 1456,
        purchases: 432,
        embedding: []
    },
    {
        name: "TRX ALL-IN-ONE Suspension Training System",
        price: 169.95,
        description: "Complete bodyweight training system with anchor, suspension straps, and workout guide. Build strength anywhere.",
        image: "https://images.unsplash.com/photo-1598971639058-fab3c3109a00",
        category: "Sports",
        brand: "TRX",
        tags: ["training", "suspension", "bodyweight", "portable"],
        rating: 4.8,
        reviewCount: 5432,
        inStock: true,
        priceRange: "$150-$200",
        views: 21543,
        clicks: 4876,
        purchases: 1876,
        embedding: []
    },
    {
        name: "Garmin Forerunner 245 GPS Running Watch",
        price: 299.99,
        description: "Advanced GPS running smartwatch with heart rate monitoring, training metrics, and smartphone notifications.",
        image: "https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1",
        category: "Sports",
        brand: "Garmin",
        tags: ["running", "GPS", "smartwatch", "fitness tracker"],
        rating: 4.7,
        reviewCount: 6789,
        inStock: true,
        priceRange: "$250-$350",
        views: 28765,
        clicks: 6234,
        purchases: 2134,
        embedding: []
    },
    {
        name: "Spalding NBA Official Game Basketball",
        price: 149.99,
        description: "Official NBA game ball with full-grain leather cover. The same basketball used in professional games.",
        image: "https://images.unsplash.com/photo-1519861531473-9200262188bf",
        category: "Sports",
        brand: "Spalding",
        tags: ["basketball", "NBA", "official", "leather"],
        rating: 4.9,
        reviewCount: 2345,
        inStock: true,
        priceRange: "$100-$200",
        views: 14532,
        clicks: 3456,
        purchases: 987,
        embedding: []
    },
    {
        name: "Bowflex SelectTech 552 Adjustable Dumbbells",
        price: 349.99,
        description: "Space-saving adjustable dumbbells that replace 15 sets of weights. Adjusts from 5 to 52.5 lbs per dumbbell.",
        image: "https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b",
        category: "Sports",
        brand: "Bowflex",
        tags: ["dumbbells", "weights", "home gym", "adjustable"],
        rating: 4.8,
        reviewCount: 8765,
        inStock: false,
        priceRange: "$300-$400",
        views: 34567,
        clicks: 7654,
        purchases: 2876,
        embedding: []
    },
    {
        name: "Under Armour HeatGear Compression Shirt",
        price: 34.99,
        description: "Moisture-wicking compression shirt with 4-way stretch fabric. Keeps you cool and dry during intense workouts.",
        image: "https://images.unsplash.com/photo-1576678927484-cc907957088c",
        category: "Sports",
        brand: "Under Armour",
        tags: ["compression", "shirt", "training", "moisture-wicking"],
        rating: 4.6,
        reviewCount: 4321,
        inStock: true,
        priceRange: "$30-$40",
        views: 16789,
        clicks: 3987,
        purchases: 1432,
        embedding: []
    },
    {
        name: "Razor A5 Lux Kick Scooter",
        price: 119.99,
        description: "Adult kick scooter with extra-large wheels and adjustable handlebars. Folds for easy transport and storage.",
        image: "https://images.unsplash.com/photo-1607853202273-797f1c22a38e",
        category: "Sports",
        brand: "Razor",
        tags: ["scooter", "transportation", "outdoor", "foldable"],
        rating: 4.5,
        reviewCount: 2109,
        inStock: true,
        priceRange: "$100-$150",
        views: 9876,
        clicks: 2234,
        purchases: 654,
        embedding: []
    },
    {
        name: "Everlast Pro Style Training Boxing Gloves",
        price: 44.99,
        description: "Professional training gloves with dense foam padding and full wrist support. Ideal for heavy bag work and mitt training.",
        image: "https://images.unsplash.com/photo-1549719386-74dfcbf7dbed",
        category: "Sports",
        brand: "Everlast",
        tags: ["boxing", "gloves", "training", "martial arts"],
        rating: 4.4,
        reviewCount: 3567,
        inStock: true,
        priceRange: "$40-$50",
        views: 12345,
        clicks: 2987,
        purchases: 876,
        embedding: []
    },
    {
        name: "Fitbit Charge 5 Fitness Tracker",
        price: 149.95,
        description: "Advanced fitness tracker with built-in GPS, stress management tools, and 7-day battery life. Tracks heart rate, sleep, and activity.",
        image: "https://images.unsplash.com/photo-1575311373937-040b8e1fd5b6",
        category: "Sports",
        brand: "Fitbit",
        tags: ["fitness tracker", "GPS", "health", "wearable"],
        rating: 4.5,
        reviewCount: 9876,
        inStock: true,
        priceRange: "$100-$200",
        views: 32145,
        clicks: 7123,
        purchases: 2543,
        embedding: []
    },
    {
        name: "Hydroflask 32 oz Water Bottle",
        price: 44.95,
        description: "Insulated stainless steel water bottle keeps drinks cold for 24 hours or hot for 12 hours. BPA-free and dishwasher safe.",
        image: "https://images.unsplash.com/photo-1602143407151-7111542de6e8",
        category: "Sports",
        brand: "Hydroflask",
        tags: ["water bottle", "hydration", "insulated", "outdoor"],
        rating: 4.8,
        reviewCount: 12456,
        inStock: true,
        priceRange: "$40-$50",
        views: 24567,
        clicks: 5678,
        purchases: 2109,
        embedding: []
    },
    {
        name: "CAP Barbell Olympic Weight Set - 300 lbs",
        price: 399.99,
        description: "Complete Olympic weight set including 7-foot barbell, weight plates, and spring collars. Perfect for home gym setup.",
        image: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48",
        category: "Sports",
        brand: "CAP Barbell",
        tags: ["weights", "barbell", "home gym", "strength training"],
        rating: 4.6,
        reviewCount: 2876,
        inStock: true,
        priceRange: "$350-$450",
        views: 11234,
        clicks: 2345,
        purchases: 543,
        embedding: []
    },
    {
        name: "Schwinn IC4 Indoor Cycling Bike",
        price: 899.99,
        description: "Magnetic resistance indoor bike with LCD monitor, tablet holder, and dual pedals. Compatible with popular cycling apps.",
        image: "https://images.unsplash.com/photo-1556817411-31ae72fa3ea0",
        category: "Sports",
        brand: "Schwinn",
        tags: ["cycling", "indoor bike", "cardio", "home fitness"],
        rating: 4.7,
        reviewCount: 5432,
        inStock: true,
        priceRange: "$800-$1000",
        views: 19876,
        clicks: 3987,
        purchases: 876,
        embedding: []
    },
    {
        name: "Franklin Sports Soccer Goal Set",
        price: 79.99,
        description: "Portable pop-up soccer goals (set of 2) with carrying case. Easy setup for backyard practice and training.",
        image: "https://images.unsplash.com/photo-1579952363873-27f3bade9f55",
        category: "Sports",
        brand: "Franklin Sports",
        tags: ["soccer", "goals", "training", "portable"],
        rating: 4.3,
        reviewCount: 1567,
        inStock: true,
        priceRange: "$70-$90",
        views: 7654,
        clicks: 1678,
        purchases: 432,
        embedding: []
    },
    {
        name: "Titleist Pro V1 Golf Balls - 1 Dozen",
        price: 54.99,
        description: "Premium golf balls with soft feel and consistent flight. Tour-proven performance for serious golfers.",
        image: "https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa",
        category: "Sports",
        brand: "Titleist",
        tags: ["golf", "balls", "premium", "tour performance"],
        rating: 4.9,
        reviewCount: 6789,
        inStock: true,
        priceRange: "$50-$60",
        views: 15432,
        clicks: 3654,
        purchases: 1876,
        embedding: []
    },
    {
        name: "SKLZ Gold Flex Strength and Tempo Trainer",
        price: 39.99,
        description: "Golf training aid to improve swing tempo, strength, and flexibility. Variable resistance for all skill levels.",
        image: "https://images.unsplash.com/photo-1592919505780-303950717480",
        category: "Sports",
        brand: "SKLZ",
        tags: ["golf", "training aid", "swing trainer", "practice"],
        rating: 4.4,
        reviewCount: 987,
        inStock: true,
        priceRange: "$30-$50",
        views: 5432,
        clicks: 1123,
        purchases: 298,
        embedding: []
    },
    {
        name: "Reebok CrossFit Nano X2 Training Shoes",
        price: 139.99,
        description: "Versatile training shoes designed for CrossFit and high-intensity workouts. Responsive cushioning with stable heel.",
        image: "https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa",
        category: "Sports",
        brand: "Reebok",
        tags: ["CrossFit", "training shoes", "gym", "athletic"],
        rating: 4.6,
        reviewCount: 3210,
        inStock: true,
        priceRange: "$130-$150",
        views: 14567,
        clicks: 3234,
        purchases: 987,
        embedding: []
    }
];


module.exports = { sportsProducts };